### ISSUE TITLE
dehydrate/rehydrate

### ISSUE THREAD

**Issue by localnerve** [yahoo/fluxible-plugin-routr#12]
Is there a reason(s) why this plugin does not have dehydrate/rehydrate functionality? It seems super useful to have it here. Covered elsewhere? Possible PR?

**Comment by redonkulus** [comment]
You can see the explanation why from the original PR here: https://github.com/yahoo/fluxible-plugin-routr/pull/1

An example of the subsequent solution is here https://github.com/yahoo/fluxible.io/blob/master/app.js#L17

**Comment by localnerve** [comment]
I read through #1, sourced [fluxible-example#37](https://github.com/yahoo/flux-examples/issues/37). @mridgway  just says ~paraphrase~"it doesn't make sense for us to be dehydrating/rehydrating routes". I was wondering about the reasoning behind this.

When sourcing the routes from a backend (not a config file), it would be a lot less custom code if fluxible supported this using the plugin architecture.
Anyways, just looking for a reason for not supporting this beyond ~"not doing this/doesn't make sense". 

I'm wondering if supporting this in my own fluxible app using the fluxible pattern is inherently wrong for some reason that you already figured out.
My plan was to use an action and service like fluxible demonstrates. The action calls a service in the bootstrap response on payload.server === true (supplied only in the server response bootstrap, The service uses a local cache to speed the TTFB). On the client the action would source it from bootstrapped state.

Admittedly, I'm a novice to fluxible, but isn't this the fluxible pattern to use actions, stores, and services? Why not allow the router plugin to participate in the isomorphic state part of this?

**Comment by mridgway** [comment]
This was an optimization for routes that are static. I think there is definitely a use case for dynamic route handling that you showed in your other PR. I think that would be useful as a separate plugin that would be used instead of this one.
