### ISSUE TITLE
Deal with 404 page?

### ISSUE THREAD

**Issue by lenage** [yahoo/fluxible-plugin-routr#16]
Hi There,
I would like to create a default 404 page for my App, so how could i do that? like a 404 component?

**Comment by redonkulus** [comment]
@lenage we haven't documented this yet, but you can see how we implemented it for our doc site. Here is the PR with the changes: https://github.com/yahoo/fluxible.io/pull/96/files

The general idea is that you register a `componentActionHandler` in your app.js file that will handle errors returned from an action. You can then dispatch a 404 action that can update your store state and display a 404 component.

**Comment by lenage** [comment]
Thank you for help, i will check out it

**Comment by gpbl** [comment]
@redonkulus how would that work server-side? 

In the examples, the 404 page is actually managed from the express server, calling the `next` middleware function. I tried today the `componentActionHandler` but it can't work server-side since the actions can't be executed in the `componentContext` (right?)

**Comment by gpbl** [comment]
IMHO it would be nicer if the `navigateAction` exposed the error to the payload (also if the route doesn't exist) so that we can use it in the RouteStore.

**Comment by redonkulus** [comment]
@gpbl its also managed in app.js to: https://github.com/yahoo/fluxible.io/blob/master/app.js#L16. The `navigateAction` will receive the error object from action so it can handle the 404 action there. It currently works on fluxible.io today. http://fluxible.io/foo.html

**Comment by gpbl** [comment]
@redonkulus awesome, thanks! that was simple!

**Comment by redonkulus** [comment]
fyi, I've opened an [issue](https://github.com/yahoo/fluxible/issues/91) on the fluxible repo to get this documented.
