### ISSUE TITLE
Routes with duplicate paths but different HTTP methods

### ISSUE THREAD

**Issue by tlovett1** [yahoo/fluxible-plugin-routr#17]
Are routes with duplicate paths but different HTTP methods possible? I would be very surprised if it wasn't.

**Comment by mridgway** [comment]
Yes, they should be. They just have to have different names I think.

**Comment by tlovett1** [comment]
I am trying to have a GET route at /login and a POST route at /login. The `page`, `title`, and route keys are different. Here is the warning I get in the console:

```
Warning: flattenChildren(...): Encountered two children with the same key, `.$/login`. Child keys must be unique; when two children share a key, only the first child will be used.
```

**Comment by Vijar** [comment]
@tlovett1 can you show me the config you use?

Something like this should work as long as the top level keys are different:
```js
{
  login_GET: {
    method: 'GET',
    path: '/login'
  },
  login_POST: {
    method: 'POST',
    path: '/login'
  }
}
```

but something like this wouldn't work:
```js
{
  login: {
    method: 'GET',
    path: '/login'
  },
  login: {
    method: 'POST',
    path: '/login'
  }
}
```
