### ISSUE TITLE
Fetcher.registerFetcher undefined

### ISSUE THREAD

**Issue by bringking** [yahoo/fluxible-plugin-routr#6]
In the latest 0.2.1 version from npm, I can't seem to register a Fetcher service. I get undefined on Fetcher.registerFetcher

      /**
	         * Registers a service to the manager
	         * @method registerService
	         */
	        registerService: function registerService(service) {
	            Fetchr.registerFetcher(service);
	        },

Is this something in my config? My usage looks like the following-

    var fetchrPlugin = require('fluxible-plugin-fetchr');
    //setup fetchr
    var pluginInstance = fetchrPlugin({
        xhrPath: '/api' // Path for XHR to be served from
    });
    app.plug(pluginInstance);
    pluginInstance.registerService(campaignService);

**Comment by Dhq** [comment]
Same issue for me with 0.2.3.

**Comment by lingyan** [comment]
Hmm...  Could you please run `npm ls fetchr` to see if `fetchr` lib is installed?

**Comment by xissy** [comment]
This code should be in `app.js`.
```
var pluginInstance = fetchrPlugin({
    xhrPath: '/api' // Path for XHR to be served from
});
app.plug(pluginInstance);
```

And this code should be in `server.js`.
```
pluginInstance.registerService(campaignService);
```

If you code both in `app.js` then you will meet the undefined error as you mentioned.
