### ISSUE TITLE
Re-use router instance between requests

### ISSUE THREAD

**Issue by klimashkin** [yahoo/fluxible-plugin-routr#9]
Now on every application context new Router instance creates with pathToRegexp on every route.
It's pretty expensive and why, if in most cases routes initialized on application start and not changed?

**Comment by mridgway** [comment]
You're right, if the routes are not changing per request then it's extra overhead. We should update it to keep the same router instance between requests.

**Comment by mridgway** [comment]
This issue was copied to https://github.com/yahoo/fluxible-router/issues/58 and will be closed in the repo as we have deprecated fluxible-plugin-routr.
